kind: pipeline
type: docker
name: ci/cd
clone:
  disable: true
steps:
  - name: clone
    image: wwma/drone-github-clone
    settings:
      SSH_KEY:
        from_secret: ssh_key
  - name: build_docker
    image: plugins/docker
    pull: if-not-exists
    settings:
      registry: hub.ooxo.cc
      username:
        from_secret: nexus_docker_username
      password:
        from_secret: nexus_docker_password
      repo: hub.ooxo.cc/home/cnpmcore
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: k8s_host
      username:
        from_secret: k8s_username
      key:
        from_secret: k8s_key
      port: 22
      command_timeout: 2m
      script:
        - echo ${DRONE_COMMIT}${DRONE_BUILD_NUMBER}
        - kubectl apply -f https://git.ooxo.cc/sonic/yaml/raw/branch/main/cnpmcore.yaml
        - kubectl set image deployment/cnpmcore cnpmcore=hub.ooxo.cc/home/cnpmcore:${DRONE_COMMIT_SHA:0:8}
